# Cache key for CircleCI. We want to invalidate the cache whenever the Bazel workspace or the
# NPM dependencies changed.
var_1: &cache_key angular-tsickle-v2-{{ checksum "WORKSPACE" }}-{{ checksum "yarn.lock" }}

# Saves the cache for the current cache key. We store the installed "node_modules" and the Bazel
# repository cache in order to make subsequent builds faster.
var_2: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"
      - "~/bazel_repository_cache"

version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn && yarn lint
      - *save_cache

  bazel:
    # Docker image for CircleCI jobs with Bazel installed. The version of Bazel is controlled
    # by the docker image version. e.g "google/bazel:0.22.0" installs Bazel v0.22.0. When updating this
    # version, consider updating the minimum required Bazel version in the "WORKSPACE" file.
    docker:
      - image: l.gcr.io/google/bazel:0.28.0
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: bazel test ...
      - *save_cache

workflows:
  version: 2
  default_workflow:
    jobs:
      - bazel
      - lint
