version: 2
jobs:
  build:
    working_directory: ~/tsickle
    docker:
      - image: insready/bazel
    steps:
      - checkout
      - restore_cache:
          key: tsickle-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Build twice, workaround for
      # https://github.com/bazelbuild/bazel/issues/3114
      - run: bazel build ... || bazel build ...
      - save_cache:
          key: tsickle-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
