# Cache key for CircleCI. We want to invalidate the cache whenever the Bazel workspace or the
# NPM dependencies changed.
var_1: &cache_key angular-tsickle-v2-{{ checksum "WORKSPACE" }}-{{ checksum "yarn.lock" }}
# Default docker image for CircleCI jobs.
# The version of Bazel is controlled by the package.json/yarn.lock files.
var_2: &default_docker_image circleci/node:10.16

# Settings common to each job
var_3: &job_defaults
  working_directory: ~/tsickle
  docker:
  - image: *default_docker_image

# Saves the cache for the current cache key. We store the installed "node_modules" and the Bazel
# repository cache in order to make subsequent builds faster.
var_4: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"
      - "~/bazel_repository_cache"

version: 2

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn && yarn test
      - *save_cache
