version: 2
jobs:
  build:
    working_directory: ~/tsickle
    docker:
      - image: alexeagle/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: tsickle-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: bazel build ...
      - save_cache:
          key: tsickle-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
